//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManager.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDetail
    {
        public int ExpenseID { get; set; }
        public string Expense_Description { get; set; }
        public int ExpenseRS { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
