//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManager.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsDetail
    {
        public int SavingID { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
        public int SalaryAmount { get; set; }
        public int ExpenseAmount { get; set; }
        public int Savings { get; set; }
    }
}
